/**
 * index.js
 * 
 * Entry point for the code generator module.
 */

const CodeGenerator = require('./CodeGenerator');

/**
 * Converts the intermediate representation (IR) to JavaScript code.
 * 
 * @param {Object} ast - The AST generated by the parser
 * @returns {string} - The generated JavaScript code
 */
function generateCode(ast, classTable) {
  const generator = new CodeGenerator();
  generator.classTable = classTable;
  return generator.generate(ast);
}

module.exports = {
  generateCode
}; 